### ISSUE TITLE
Be able to choose the method for display user information in navbar

### ISSUE THREAD

**Issue by BenjaminDigeon** [TrestleAdmin/trestle-auth#10]
I had a hard time configuring my user's email in the navbar, let me explain why.

I have a `User` model with a optional `username` and i want to display in the navbar the `email` of the login user.

Currently there are 2 options for display user information in the navbar next to the avatar.

First having a `first_name` and a `last_name` in your model : 

https://github.com/TrestleAdmin/trestle/blob/master/lib/trestle/display.rb
```ruby
module Trestle::Auth::UserHelper
  def format_user_name(user)
    if user.respond_to?(:first_name) && user.respond_to?(:last_name)
      safe_join([user.first_name, content_tag(:strong, user.last_name)], " ")
    else
      display(user)
    end
  end
```

And if not trestle auth use the display method from trestle :

https://github.com/TrestleAdmin/trestle/blob/master/app/helpers/trestle/display_helper.rb
```ruby
module Trestle
  class Display
    def initialize(instance)
      @instance = instance
    end

    def to_s
      if display_method != :to_s || @instance.method(display_method).source_location
        @instance.public_send(display_method)
      else
        "#{@instance.class} (##{@instance.id})"
      end
    end

  private
    def display_method
      @display_method ||= Trestle.config.display_methods.find { |m| @instance.respond_to?(m) } || :to_s
    end
  end
end
```

Who look into a configuration array with a list of methods, here are the default one
https://github.com/TrestleAdmin/trestle/blob/master/lib/trestle/configuration.rb#L67
```ruby
option :display_methods, [:display_name, :full_name, :name, :title, :username, :login, :email]
```

That nice but if you have in my case a optional attributes in the array before another email, it's gonna be use even if it is empty.

So my solution was to change the array order in trestle initializer.

```ruby
config.display_methods = [:display_name, :full_name, :name, :title, :email, :username, :login]
```

But if i want to display the username if present or the email if not i can't with this method.

Not a big issue but it would be nice to have an optional block like the avatar for configuring that.

Thanks for your time and realy loving the trestle gems 😃

**Comment by spohlenz** [comment]
This is definitely a good idea to make this fully customizable. I'll aim to implement this as soon as I can.

**Comment by BenjaminDigeon** [comment]
@spohlenz Perfect ! Thanks :smiley:
