### ISSUE TITLE
i want to override a function in lib trestle auth. how do i do it ? 

### ISSUE THREAD

**Issue by hoangnv2107** [TrestleAdmin/trestle-auth#24]
Example: i want to override function remember_me!. You can see this image below. 
<img width="706" alt="Screen Shot 2019-08-07 at 17 49 46" src="https://user-images.githubusercontent.com/45548185/62617315-c7ee4100-b93b-11e9-948a-b0b6159eeaf4.png">

**Comment by hoangnv2107** [comment]
hi Mr @spohlenz you can help me. thanks you very much

**Comment by bkwaku** [comment]
@hoangnv2107 how did you override trestle methods?
