### ISSUE TITLE
Is it possible to override load_collection on Controller? (trestle-auth)

### ISSUE THREAD

**Issue by BambangSinaga** [TrestleAdmin/trestle-auth#26]
So, I have installer trestle-auth.
I want to generate all of data on each model which related to current_user.

So, I tried to write association between each. For example:
```ruby
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable

  has_many :events
end
```

```ruby
class Event < ApplicationRecord
  belongs_to :administrator
end
```

I already have row event in the database:
```
=> #<Event id: "daff8dd6-6ba5-4396-886c-78d95d65690b", administrator_id: "17c6a6d0-ffac-4aad-9c31-1c9a0d609bf7", title: "Wonderfull Toba Lake">
```

and I tried to get all of current_user.events on `Event` page
```ruby
Trestle.resource(:events) do
  before_action only: :index do
    self.collection = current_user.events
  end
  # ...
end
```

But got this error
<img width="1440" alt="Screen Shot 2019-12-07 at 16 44 20" src="https://user-images.githubusercontent.com/4920541/70372407-28ed4c00-1911-11ea-956c-b88f83b40af5.png">

Any solution @spohlenz ?

**Comment by spohlenz** [comment]
Rather than using a `before_action` block, try simply overriding the `collection` block:

```ruby
Trestle.resource(:events) do
  collection do
    current_user.events
  end
end
```

That will set the base scope for all actions within the events admin.

**Comment by BambangSinaga** [comment]
Wow, cool man.. I tried to figured it out the whole day

Thank you so much for your help
