### ISSUE TITLE
Conflict with ActiveModel has_secure_password when using with Devise backend

### ISSUE THREAD

**Issue by nielspetersen** [TrestleAdmin/trestle-auth#27]
Hello, 

### Problem
I my my local environment:
ruby - 2.4.6
rails - 4.2.10
trestle-0.9.2
trestle-auth-0.40,

I was facing the following error, when trying to update the password at `/admin/auth/users/:id`:

> NoMethodError in Auth::UsersAdmin::AdminController#update
> undefined method `password_digest=' for #<User:0x00007ff31b87c6f0>
> Did you mean?  password_digest#

A similiar error occured when trying to change the password or creating a user in the Rails console:

e.g. User.find(1).reset_password('<new_password>', '<new_password>') 

```
User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
NoMethodError: undefined method `password_digest=' for #<User:0x00007fe52ce0dbc0>
Did you mean?  password_digest
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activemodel-4.2.10/lib/active_model/attribute_methods.rb:433:in `method_missing'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activemodel-4.2.10/lib/active_model/secure_password.rb:125:in `password='
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/devise-4.6.2/lib/devise/models/recoverable.rb:39:in `reset_password'
        from (irb):1
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from /Users/nielspetersen/Dev/rails/e-mobility-catalog/bin/rails:9:in `<top (required)>'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/spring-2.1.0/lib/spring/commands/rails.rb:6:in `call'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/spring-2.1.0/lib/spring/command_wrapper.rb:38:in `call'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/spring-2.1.0/lib/spring/application.rb:215:in `block in serve'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/spring-2.1.0/lib/spring/application.rb:175:in `fork'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/spring-2.1.0/lib/spring/application.rb:175:in `serve'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
        from /Users/nielspetersen/.rvm/gems/ruby-2.4.6/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/nielspetersen/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/nielspetersen/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'

```
## Solution proposal:

Since devise does not use password_digest but encrypted_password, the following two workarounds might help.

**1. Add instruction in wiki to remove following lines from User model (since they have been added during `rails generate trestle:auth:install User --devise`):**

```ruby
include Trestle::Auth::ModelMethods
include Trestle::Auth::ModelMethods::Rememberable
```
or 

**2. Disable "has_secure_password" when using Devise backend**

```ruby
# lib/trestle/auth/model_methods.rb
included do
    has_secure_password unless Trestle.config.auth.backend == :devise
end	     
```

**Comment by hdbreaker** [comment]
Hi guys, I'm having this exact issue and I do not know how to resolve it, always that I try to create a new Admin User I get the following error:

```
2.6.3 :001 > Administrator.create(email: "admin@example.com", password: "password", first_name: "Admin", last_name: "User")
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `password_digest=' for #<Administrator:0x00007fcb73088478>)
Did you mean?  password=
```

This is pretty frustrating, I removed all the has_secure_password in all my models, and I remove password_digest from Database.

Can you explain to me a workaround to this issue?

**Comment by hdbreaker** [comment]
When I removed the lines: 

include Trestle::Auth::ModelMethods
include Trestle::Auth::ModelMethods::Rememberable

As nielspetersen recommended I got the following error:

<img width="1013" alt="Screen Shot 2020-05-25 at 19 24 54" src="https://user-images.githubusercontent.com/5799585/82833114-70ff2b80-9ebd-11ea-9fd7-a0d9ca8f670d.png">

I need to fix this issue as soon as possible!

Thank ahead!

**Comment by spohlenz** [comment]
When using trestle-auth with the Devise integration, it is assumed that you are bringing your own Devise model, i.e. a model that looks something like this:

```ruby
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end
```

which is created when you run `rails generate devise User`.

If you then have the following lines in your `config/initializers/trestle.rb` then you should be good to go:

```ruby
# Set the authentication backend to use Devise.
config.auth.backend = :devise

# Specify the Devise/Warden mapping/scope.
config.auth.warden.scope = :user

# Specify the user class to be used by trestle-auth.
config.auth.user_class = -> { User }
```

These lines are added when you run `rails generate trestle:auth:install User --devise`. If you run this generator (and the Devise generator above) with `Administrator` instead of `User` then it should also adapt automatically.

Note that the `Trestle::Auth::ModelMethods` modules should *not* be included in your user model in this case, since Devise brings that functionality instead. They also should not be added automatically by the generator, so I am not sure where you are seeing that @nielspetersen.

This could probably be made clearer in the README so apologies for any confusion.

**Comment by nielspetersen** [comment]
@spohlenz Thank you for the answer.
I am using a Devise user model and used the `--devise` flag during the installation. Somehow it has been added. 

@hdbreaker Does the answer from Sam help?

**Comment by hdbreaker** [comment]
Hi guys, I was able to make it work, could be great to improve Trestle documentation it is really difficult to get deep with the framework due to the lack of documentation, anyway, I love the project, I think that is the best Rails Admin Panel around Internet! Nice job!
