### ISSUE TITLE
Somehow when devise is being used, scopes become obsolete?

### ISSUE THREAD

**Issue by jeffbdavenport** [TrestleAdmin/trestle-auth#32]
I installed the plugin with
```bash
$ rails generate trestle:auth:install User --devise
```

I have this config value set in the config, however, it allows ALL users in regardless of whether admin is set to `true`, `false`, or `nil` on the respective user.

```ruby
config.auth.user_scope = -> { User.where(admin: true) }
```

**Comment by spohlenz** [comment]
Some of the configuration options including `config.auth.user_scope` do not take any effect when using a Devise or Warden backend. Only the relevant options should be added to `config/initializers/trestle.rb` when running the install generator with the `--devise` option.

You might wish to look into Devise/Warden scopes and use an admin scope just for Trestle. Alternatively you can set up a global `before_action` within `config/initializers/trestle.rb` to do the admin authorization:

```ruby
config.before_action do
  redirect_to "/" if logged_in? && !current_user.admin?
end
```

You may also be interested in the current state of the [authorization](https://github.com/TrestleAdmin/trestle-auth/tree/authorization) branch which I hope to finish off and release soon.

**Comment by jeffbdavenport** [comment]
> Alternatively you can set up a global `before_action` within `config/initializers/trestle.rb` to do the admin authorization:
> 
> ```ruby
> config.before_action do
>   redirect_to "/" if logged_in? && !current_user.admin?
> end
> ```

This is exactly what I was looking for! Thank you, this works perfectly
