### ISSUE TITLE
can not login if "config.authentication_keys" in devise is not ":email"

### ISSUE THREAD

**Issue by chenjau** [TrestleAdmin/trestle-auth#33]
Hi,
just figured it out that if config.authentication_keys in config/initializers/devise.rb is not :email, trestle-auth login will fail.
thanks.

reference: [How To: Allow users to sign in using their username or email address](https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address)

**Comment by spohlenz** [comment]
You can set `config.auth.authenticate_with` to the name of your login parameter (e.g. `:login` or `:username`). In trestle-auth 0.4.3, I have updated the Devise generator to automatically choose the most appropriate (single) field based on `Devise.authentication_keys`.

Apologies for the very late response.
