### ISSUE TITLE
Which version of trestle-auth to use?

### ISSUE THREAD

**Issue by quantavi** [TrestleAdmin/trestle-auth#34]
When using latest version of trestle-auth the lib seems to be missing authorize_with method. We need to use trestle-auth from authorization:

`gem 'trestle-auth', github: 'TrestleAdmin/trestle-auth', branch: 'authorization', ref: '7d164117a60ffb46f657c721874c01950c64a566'`

Are we doing something wrong and should be using version from master? Or even better, use some released version? We are using CanCanCan for authorization. Thanks

**Comment by spohlenz** [comment]
At the time of writing, `7d164117a60ffb46f657c721874c01950c64a566` is the latest commit in the authorization branch. It is close to being ready, and I am using it in production in my own apps, but requires a little further refinement before I merge it into `master`.

Can you describe in more detail how you are trying to use `authorize_with` and the error (and backtrace) you are seeing?

**Comment by quantavi** [comment]
Apparently, we had some problem with initialization. We have got back to:

`gem 'trestle-auth', github: 'TrestleAdmin/trestle-auth', branch: 'authorization', ref: '7d164117a60ffb46f657c721874c01950c64a566'`

and got it working. Thanks

**Comment by kxu1988** [comment]
> At the time of writing, `7d164117a60ffb46f657c721874c01950c64a566` is the latest commit in the authorization branch. It is close to being ready, and I am using it in production in my own apps, but requires a little further refinement before I merge it into `master`.
> 
> Can you describe in more detail how you are trying to use `authorize_with` and the error (and backtrace) you are seeing?

I use the Gem
`gem 'trestle-auth', github: 'TrestleAdmin/trestle-auth', branch: 'authorization', ref: '7d164117a60ffb46f657c721874c01950c64a566'`

the other version info is:
Rails  6.0.3.4
trestle 0.9.4
ruby 2.6.5
`=> Booting Puma
=> Rails 6.0.3.4 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
        84: from bin/rails:3:in `<main>'
        83: from bin/rails:3:in `load'
        82: from /home/kxu/github/bashiends/bin/spring:15:in `<top (required)>'
        81: from /home/kxu/github/bashiends/bin/spring:15:in `require'
        80: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        79: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        78: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        77: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        76: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        75: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        74: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        73: from /home/kxu/github/bashiends/bin/rails:9:in `<top (required)>'
        72: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
        71: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
        70: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
        69: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        68: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        67: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        66: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        65: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        64: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
        63: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
        62: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
        61: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        60: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        59: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        58: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
        57: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `tap'
        56: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        55: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:37:in `start'
        54: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
        53: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        52: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        51: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        50: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        49: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        48: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        47: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        46: from config.ru:3:in `block in <main>'
        45: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
        44: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
        43: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
        42: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
        41: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        40: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        39: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        38: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        37: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        36: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        35: from /home/kxu/github/bashiends/config/environment.rb:5:in `<main>'
        34: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
        33: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
        32: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        31: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        30: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        29: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
        28: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
        27: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        26: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
        25: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:415:in `call'
        24: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
        23: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `each'
        22: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        21: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        20: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        19: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        18: from /home/kxu/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        17: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
        16: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
        15: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
        14: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `block in <class:Engine>'
        13: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `each'
        12: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
        11: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:665:in `load_config_initializer'
        10: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
         9: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/engine.rb:666:in `block in load_config_initializer'
         8: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
         7: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
         6: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
         5: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
         4: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
         3: from /home/kxu/github/bashiends/config/initializers/trestle.rb:1:in `<main>'
         2: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/trestle-0.9.4/lib/trestle.rb:53:in `configure'
         1: from /home/kxu/.rvm/gems/ruby-2.6.5/gems/trestle-0.9.4/lib/trestle/configurable.rb:8:in `configure'
/home/kxu/github/bashiends/config/initializers/trestle.rb:143:in `block in <main>': undefined method `authorize_with' for #<Trestle::Configuration> (NoMethodError)`
