### ISSUE TITLE
Inline auth loop with trestle-auth (with devise) and trestle-sidekiq

### ISSUE THREAD

**Issue by vasilybodnarchuk** [TrestleAdmin/trestle-auth#36]
I use trestle-auth that integrated with devise. No problem with it. I can easily login to admin trestle. The problem appeared when I try to open sidekiq (after success auth) I see login form. How can I fix that? 

<img width="1719" alt="Screen Shot 2021-03-20 at 9 52 19 AM" src="https://user-images.githubusercontent.com/7932474/111871703-f9295280-8961-11eb-9f2c-7d3ec5ecf1b0.png">

**Comment by spohlenz** [comment]
This should be fixed now in trestle-auth 0.4.3. The routing constraint class (`Trestle::Auth::Constraint`) had not been updated to use the newer authentication backends system.
