### ISSUE TITLE
looks like `find_by` is not plays well with trestles' sequel adapter

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle-auth#4]
https://github.com/TrestleAdmin/trestle-auth/blob/6128fe3ce818e416b0eb1501b5de317a6275d3fc/lib/trestle/auth/configuration.rb#L26

throws me a NoMethod error for `AdminUser < Sequel::Model` class

**Comment by spohlenz** [comment]
The `config.auth.find_user` block will need to be manually specified for non-ActiveRecord ORMs as it does not hook into the regular Trestle adapters.

This can be done in your `config/initializers/trestle.rb` file with something like:

```ruby
config.auth.find_user = ->(id) {
  AdminUser[id]
}
```

Note that there was an error in the `trestle-auth` install generator (the configuration block was labeled as `config.auth.remember.find_user`) which has now been addressed.

**Comment by okliv** [comment]
ok. i see... thanks

can it be somehow DRYed with another config option:

`config.auth.user_class = -> { MyCustomAdminUser }`

?

**Comment by spohlenz** [comment]
You could specify it as:

```
config.auth.user_class = -> { MyCustomAdminUser }
config.auth.find_user = ->(id) {
  Trestle.config.auth.user_class[id]
}
```

They'd both need to still be specified, so you wouldn't be saving much. However the `find_user` config (and potentially other settings) could possibly be moved into their own initializer or gem that would become a compatibility layer for Sequel.

**Comment by okliv** [comment]
i have 0.8.9 trestle and 0.2.4 trestle-auth, appears that `config.auth.find_user` in trestle config is ignored. no matter i define there i still get NoMethod error about `find_by`
