### ISSUE TITLE
redirect_on_login config not working in staging env

### ISSUE THREAD

**Issue by dmbrooking** [TrestleAdmin/trestle-auth#42]
In my config, I have

```
config.auth.redirect_on_login = -> { CreatorAdmin.path(:show) }
```
and the resource for that looks like this:
```
Trestle.resource(:creator, singular: true, path: 'me', class: Creator) do
  instance { current_user }
....
```

in my dev env, after I log in, it redirects me to `/me` as I'd expect. When I deploy to Heroku and login, I get an error because it's trying to redirect me to the index view of a random resource that I've disabled index views on (so it fails).

Any idea why this would work in development but not staging?

**Comment by spohlenz** [comment]
Just to clarify, is the unexpected redirect on production happening on login (i.e. after submitting the login form), or after directly accessing the admin root URL (e.g. https://example.com/admin) when already logged in?

The latter will use the current dashboard logic defined [here](https://github.com/TrestleAdmin/trestle/blob/master/app/controllers/trestle/dashboard_controller.rb), which will generally redirect to the first admin in the navigation.

**Comment by dmbrooking** [comment]
Both actually. On login and also just browsing to the root URL when already logged in.

I was wondering if it was menu related. I have the menu hidden and don't have any menu items defined (it's meant more as a dashboard for a single resource).  Let me try and add a menu config to the resource I want to work and see if that fixes it.
