### ISSUE TITLE
How to make the api to access the site?

### ISSUE THREAD

**Issue by x-ror** [TrestleAdmin/trestle-auth#5]
How to implement api correctly to enter the site. (E.g. via the client android)
What parameters do I need to send, or do I need to override the login controller? 
Do I need to make a token for the user?

**Comment by okliv** [comment]
+1

any advices how correctly we can access trestle's data via json response like https://example.com/admin/contacts.json?q=john (i use trestle-search also)

**Comment by okliv** [comment]
For now i just overridden `require_authenticated_user` method:

```ruby
Trestle.resource ..... do
    
    #.... 

    controller do
      def require_authenticated_user
        if request.path_parameters[:format] == 'json'# some any other checks like request.xhr?&&action_name=='index' && params[:token]=='secret'
          render json: admin.prepare_collection(params).to_json
        else
          super
        end
      end
    end

end

will be grateful for any other more correct way to do this
