### ISSUE TITLE
Cannot Create User With Devise and Model Methods

### ISSUE THREAD

**Issue by bendangelo** [TrestleAdmin/trestle-auth#55]
This has_secure_password cannot be used with Devise. https://github.com/TrestleAdmin/trestle-auth/blob/3fc56a67bd77fd0f8ac0872e0e94d0b3908ec9dd/lib/trestle/auth/model_methods.rb#L9

See here: https://github.com/heartcombo/devise/issues/1845

**Comment by spohlenz** [comment]
The docs probably need a little reworking, but the `Trestle::Auth::ModelMethods` concern isn't intended to be used when using the Devise integration. Running the `trestle:auth:install` generator with the `--devise` option should add the relevant auth configuration ([devise.rb.erb](https://github.com/TrestleAdmin/trestle-auth/blob/main/lib/generators/trestle/auth/install/templates/devise.rb.erb)) for an existing Devise-based user model.

**Comment by bendangelo** [comment]
Yeah I see what happened. I ran it without --devise first
