### ISSUE TITLE
Is it possible to use trestle-auth outside trestle? 

### ISSUE THREAD

**Issue by okliv** [TrestleAdmin/trestle-auth#7]
I need to implement an authorization at front-side of my application and, reasonably, do not want to use one more authentication gem..

 Is it possible to use trestle-auth for additional User class (not AdminUser used for backstage) to completely separate these two entities, first of all for security reasons (to make sure no one User can access /admin place)

thanks

**Comment by spohlenz** [comment]
It is not my intention to allow the authentication components of trestle-auth to be integrated into the application front-end -- maybe I'll extract it into a separate gem someday but it is not a priority.

I would however like the reverse to be possible -- it should be possible to have trestle-auth use your app's existing Devise, Warden or other authentication. This is partially possible already with some of the configuration options. However I do need to test this further to ensure it is supported (and documented) 100%.

**Comment by okliv** [comment]
i see. i would propose 'clearance' to the list then
