### ISSUE TITLE
Can't set the locale based on request params

### ISSUE THREAD

**Issue by rbngzlv** [TrestleAdmin/trestle-auth#8]
Hi,

I'm having trouble changing the locale in `trestle`, let me explain:

I'm using the `routing-filter` gem that removes the `locale` segment from the url and add it to the params hash, so you can set the locale in a `before_action`, like this:

```rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end
``` 

Ok, so I added a `before_action` in the `trestle` initializer:

```rb
config.before_action do |controller|
  # Rails.logger.debug("Before action")
  I18n.locale = params[:locale] || I18n.default_locale
end
```

But this doesn't work, and I think that the cause is the `around_action` present in this gem:

```rb
around_action :set_locale, if: :logged_in?

def set_locale
  I18n.with_locale(Trestle.config.auth.locale(current_user) || I18n.default_locale) { yield }
end
```

The problem is that I don't have access to the params inside the `proc`, so I can't return the desired locale.

- Do you know another way to acompplish this?
- Maybe we can add a configuration to disable this `around_action`?

Thanks for your time and this good gems!

**Comment by rbngzlv** [comment]
@spohlenz friendly ping! 😄

**Comment by spohlenz** [comment]
Apologies for the delay. I have a bit of a backlog of Trestle work to catch up on.

In 3b3196b, I have added the ability to disable the locale and time_zone around actions by setting:

```ruby
config.auth.locale = false
```

or

```ruby
config.auth.time_zone = false
```

I'm hoping this suits your use case.

**Comment by rbngzlv** [comment]
Yes, tested and works perfectly! Thanks!
